#!/usr/bin/env node
/* =========================================================================
 * convert.js — turn the raw Khan Academy program into a browser-ready
 * game.js.
 *
 *     node tools/convert.js path/to/khan-source.js
 *
 * The point of doing this with a script rather than by hand is fidelity:
 * the game logic is copied byte for byte, and only the small, enumerated
 * set of edits below is applied. Every edit must match exactly once or the
 * tool refuses to write anything, so a silent partial conversion is not
 * possible.
 *
 * What gets removed, and why:
 *
 *   1. The DeKhan block. It rewrites its own source with regular
 *      expressions and rebuilds functions through the Function constructor
 *      in order to strip Khan Academy's infinite-loop guard. Off Khan
 *      Academy there is no guard to strip, and the block's internals —
 *      notably reassigning `frameCount` to a function to capture the global
 *      object — actively break a normal page.
 *
 *   2. `DeKhan.loopDetect(...)` around the draw assignment, which becomes a
 *      plain function assignment.
 *
 *   3. The PJSCodeInjector line inside draw(), which reaches into Khan
 *      Academy's own injector internals.
 *
 * Deliberately left alone: setKALoopTimeout (runtime.js provides
 * KAInfiniteLoopSetTimeout as a no-op, so it runs harmlessly), the new__
 * helper (valid JavaScript as written), size(600, 600, JAVA2D), and the
 * try/catch in draw() including its infiniteLoopNodeType check.
 * ========================================================================= */
"use strict";

const fs = require("fs");
const path = require("path");

const inPath = process.argv[2];
const outPath = process.argv[3] ||
  path.join(__dirname, "..", "game.js");

if (!inPath) {
  console.error("usage: node tools/convert.js <khan-source.js> [out.js]");
  process.exit(1);
}

let src = fs.readFileSync(inPath, "utf8");
const original = src;
const report = [];

function fail(msg) {
  console.error("\n  CONVERSION ABORTED: " + msg);
  console.error("  Nothing was written. The source may be a different " +
                "version than expected.\n");
  process.exit(2);
}

function countOf(needle) {
  return src.split(needle).length - 1;
}

/* ---- 1. excise the DeKhan block ---------------------------------------- */
const DEKHAN_START = "var DeKhan = (function() {";
{
  const n = countOf(DEKHAN_START);
  if (n !== 1) fail("expected exactly 1 DeKhan block, found " + n);
  const start = src.indexOf(DEKHAN_START);
  const end = src.indexOf("})();", start);
  if (end === -1) fail("could not find the end of the DeKhan block");
  const removed = src.slice(start, end + "})();".length);
  src = src.slice(0, start) +
        "/* DeKhan block removed by tools/convert.js — Khan Academy " +
        "loop-guard stripping is not applicable outside KA. */" +
        src.slice(end + "})();".length);
  report.push("removed DeKhan block (" + removed.split("\n").length + " lines)");
}

/* ---- 2. unwrap the draw assignment ------------------------------------- */
{
  const NEEDLE = "draw = DeKhan.loopDetect(function() {";
  const n = countOf(NEEDLE);
  if (n !== 1) fail("expected exactly 1 wrapped draw assignment, found " + n);
  src = src.replace(NEEDLE, "draw = (function() {");
  report.push("unwrapped draw = DeKhan.loopDetect(...)");
}

/* ---- 3. drop the PJSCodeInjector poke ---------------------------------- */
{
  const re = /this\.PJSCodeInjector\.prototype\.hasOrHadDrawLoop\s*=\s*function\s*\(\)\s*\{[\s\S]*?\};/;
  const m = src.match(re);
  if (!m) fail("could not find the PJSCodeInjector assignment inside draw()");
  src = src.replace(re, "/* PJSCodeInjector poke removed by tools/convert.js */");
  report.push("removed PJSCodeInjector.hasOrHadDrawLoop assignment");
}

/* ---- sanity checks ------------------------------------------------------ */
if (/\bDeKhan\b/.test(src.replace(/\/\*[\s\S]*?\*\//g, ""))) {
  fail("a reference to DeKhan survived the conversion");
}

/* Syntax-check before writing so a bad result never reaches the repo. */
try {
  new Function(src);
} catch (e) {
  fail("converted source does not parse: " + e.message);
}

const header =
  "/* Night of the Ninja — generated by tools/convert.js\n" +
  " * Do not edit by hand. Re-run the converter against the original\n" +
  " * Khan Academy source instead, so the game logic stays byte-identical.\n" +
  " *\n" +
  " * Applied edits:\n" +
  report.map(r => " *   - " + r).join("\n") + "\n" +
  " */\n\n";

fs.writeFileSync(outPath, header + src, "utf8");

const removed = original.length - src.length;
console.log("\n  wrote " + path.relative(process.cwd(), outPath));
report.forEach(r => console.log("    - " + r));
console.log("    " + src.split("\n").length + " lines out; " + removed +
            " bytes of Khan Academy scaffolding removed, " +
            "game logic untouched\n");
